apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: kind
        image: client:0.0.1-SNAPSHOT
        name: client
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: client
status: {}
