apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client2
  name: client2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: client2
  type: ClusterIP
