apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: backend:0.0.1-SNAPSHOT
        name: backend
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: backend
status: {}
