apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: spiffe
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:/run/spire/sockets/spire-agent.sock
        image: backend:0.0.1-SNAPSHOT
        name: backend
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: java-security
          mountPath: /layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties
          subPath: java-security.properties
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
        - name: keystore
          mountPath: /home/cnb/.keystore
      serviceAccountName: backend
      volumes:
      - name: java-security
        configMap:
          name: backend-java-security
      - name: keystore
        emptyDir: {}
      - name: spire-agent-socket
        hostPath:
          # path: /run/spire/sockets
          path: /run/spire/agent-sockets
          type: Directory
status: {}
