apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client4
  name: client4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client4
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: kind
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/spire-agent.sock
          image: client4:0.0.1-SNAPSHOT
          name: client4
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: spire-workload-api
              mountPath: /run/spire/sockets
              readOnly: true
#          startupProbe:
#            httpGet:
#              scheme: HTTP
#              port: 8080
#              path: /actuator/health/readiness
#            periodSeconds: 5
#            successThreshold: 1
#            failureThreshold: 12
#            timeoutSeconds: 1
#          livenessProbe:
#            httpGet:
#              scheme: HTTP
#              port: 8080
#              path: /actuator/health/liveness
#            periodSeconds: 5
#            successThreshold: 1
#            failureThreshold: 2
#            timeoutSeconds: 1
#          readinessProbe:
#            httpGet:
#              scheme: HTTP
#              port: 8080
#              path: /actuator/health/readiness
#            periodSeconds: 5
#            successThreshold: 2
#            failureThreshold: 5
#            timeoutSeconds: 1
      serviceAccountName: client4
      volumes:
        - name: spire-workload-api
          csi:
            driver: csi.spiffe.io
            readOnly: true
status: {}
