apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: server3
  name: server3
spec:
  ports:
  - name: http
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: server3
  type: ClusterIP
