apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: client
          image: ghcr.io/spiffe/spire-agent:1.5.1
          command: ["/opt/spire/bin/spire-agent"]
          # args: [ "api", "watch",  "-socketPath", "/run/spire/sockets/agent.sock" ]
          args: [ "api", "watch",  "-socketPath", "/run/spire/sockets/spire-agent.sock" ]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: share
              mountPath: /run/share
        - name: console
          image: nginx:mainline
          volumeMounts:
            - name: share
              mountPath: /run/share
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            # path: /run/spire/sockets
            path: /run/spire/agent-sockets
            type: Directory
        - name: share
          emptyDir: {}